version: '3'
services:
  python-service:
    build: ./backend/python-service
    ports:
      - "5000:5000"
  go-service:
    build: ./backend/go-service
    ports:
      - "8080:8080"
  frontend:
    image: nginx:latest 
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

