name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        ports:
          - 2375:2375
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test services
        run: |
          docker-compose up -d
          sleep 15
          docker-compose ps
          docker-compose run docker-compose_python-service_1 pytest
          docker-compose down

